use {
    super::{
        asset_owner::TextureAtlasOwner,
        player::{self, Player},
        tile::{self, Tile, TILE_SIZE},
        GameState,
    },
    bevy::prelude::*,
    rand::Rng,
};

pub const LEVEL_SIZE: Vec3 = Vec3::new(22., 27., 2.);

#[repr(usize)]
#[derive(Copy, Clone)]
pub enum LevelObject {
    BedsideTable,
    BigTvLeft,
    BigTvRight,
    BottomLeftCorner,
    BottomLeftWall,
    BottomRightCorner,
    BottomRightWall,
    BottomWall,
    Box,
    BrokenFloor,
    Bush,
    Chair,
    CoffeeTable,
    CouchLeft,
    CouchMiddle,
    CouchRight,
    Countertop,
    Debris,
    Dirt,
    DoubleBedLeftBody,
    DoubleBedLeftFootboard,
    DoubleBedLeftHeadboard,
    DoubleBedRightBody,
    DoubleBedRightFootboard,
    DoubleBedRightHeadboard,
    FallenLeaves,
    Floor,
    Grass,
    Gravel,
    LeftWall,
    Marble,
    Nothing,
    OilSpill,
    Player,
    Recliner,
    RightWall,
    ShatteredGlass,
    SingleBedBody,
    SingleBedFootboard,
    SingleBedHeadboard,
    Sink,
    SmallTv,
    Stove,
    TopLeftCorner,
    TopLeftWall,
    TopRightCorner,
    TopRightWall,
    TopWall,
    TreeBottomLeft,
    TreeBottomRight,
    TreeTopLeft,
    TreeTopRight,
    UShapedWall,
    Water,
    WoodPlank,
}

impl LevelObject {
    pub fn id(self) -> usize {
        match self {
            Self::BedsideTable => 478,
            Self::BigTvLeft => 532,
            Self::BigTvRight => 531,
            Self::BottomLeftCorner => 172,
            Self::BottomLeftWall => 151,
            Self::BottomRightCorner => 171,
            Self::BottomRightWall => 152,
            Self::BottomWall => 203,
            Self::Box => {
                let mut thread_rng = rand::thread_rng();
                if thread_rng.gen::<bool>() {
                    thread_rng.gen_range(128..=129)
                } else {
                    thread_rng.gen_range(155..=156)
                }
            }
            Self::BrokenFloor => rand::thread_rng().gen_range(98..=100),
            Self::Bush => {
                let mut thread_rng = rand::thread_rng();
                if thread_rng.gen::<bool>() {
                    182
                } else {
                    209
                }
            }
            Self::Chair => 477,
            Self::CoffeeTable => 505,
            Self::CouchLeft => 502,
            Self::CouchMiddle => 501,
            Self::CouchRight => 500,
            Self::Countertop => 320,
            Self::Debris => rand::thread_rng().gen_range(291..=292),
            Self::Dirt => rand::thread_rng().gen_range(4..=5),
            Self::DoubleBedLeftBody => 76,
            Self::DoubleBedLeftFootboard => 49,
            Self::DoubleBedLeftHeadboard => 103,
            Self::DoubleBedRightBody => 75,
            Self::DoubleBedRightFootboard => 48,
            Self::DoubleBedRightHeadboard => 102,
            Self::FallenLeaves => 212,
            Self::Floor => 96,
            Self::Grass => rand::thread_rng().gen_range(0..=3),
            Self::Gravel => rand::thread_rng().gen_range(6..=9),
            Self::LeftWall => 175,
            Self::Marble => 11,
            Self::OilSpill => 319,
            Self::Recliner => 504,
            Self::RightWall => 176,
            Self::ShatteredGlass => {
                let mut thread_rng = rand::thread_rng();
                if thread_rng.gen::<bool>() {
                    263
                } else {
                    290
                }
            }
            Self::SingleBedBody => 74,
            Self::SingleBedFootboard => 47,
            Self::SingleBedHeadboard => 101,
            Self::Sink => 322,
            Self::SmallTv => 536,
            Self::Stove => 323,
            Self::TopLeftCorner => 199,
            Self::TopLeftWall => 124,
            Self::TopRightCorner => 198,
            Self::TopRightWall => 125,
            Self::TopWall => 202,
            Self::TreeBottomLeft => 207,
            Self::TreeBottomRight => 208,
            Self::TreeTopLeft => 180,
            Self::TreeTopRight => 181,
            Self::UShapedWall => 123,
            Self::Water => rand::thread_rng().gen_range(18..=19),
            Self::WoodPlank => 264,
            Self::Player | Self::Nothing => usize::MAX,
        }
    }
}

const LEVEL_LAYOUT: [[[LevelObject; LEVEL_SIZE.x as usize]; LEVEL_SIZE.y as usize];
    LEVEL_SIZE.z as usize] = [
    [
        [LevelObject::Grass; LEVEL_SIZE.x as usize],
        [LevelObject::Grass; LEVEL_SIZE.x as usize],
        [LevelObject::Grass; LEVEL_SIZE.x as usize],
        [LevelObject::Grass; LEVEL_SIZE.x as usize],
        [
            LevelObject::Grass,
            LevelObject::Grass,
            LevelObject::Grass,
            LevelObject::Grass,
            LevelObject::Grass,
            LevelObject::Grass,
            LevelObject::Grass,
            LevelObject::Grass,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Grass,
            LevelObject::Grass,
            LevelObject::Grass,
            LevelObject::Grass,
            LevelObject::Grass,
            LevelObject::Grass,
            LevelObject::Grass,
            LevelObject::Grass,
        ],
        [
            LevelObject::Grass,
            LevelObject::Grass,
            LevelObject::Grass,
            LevelObject::Grass,
            LevelObject::Grass,
            LevelObject::Grass,
            LevelObject::Grass,
            LevelObject::Grass,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Grass,
            LevelObject::Grass,
            LevelObject::Grass,
            LevelObject::Grass,
            LevelObject::Grass,
            LevelObject::Grass,
            LevelObject::Grass,
            LevelObject::Grass,
        ],
        [
            LevelObject::Grass,
            LevelObject::Grass,
            LevelObject::Grass,
            LevelObject::Grass,
            LevelObject::Grass,
            LevelObject::Grass,
            LevelObject::Grass,
            LevelObject::Grass,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Grass,
            LevelObject::Grass,
            LevelObject::Grass,
            LevelObject::Grass,
            LevelObject::Grass,
            LevelObject::Grass,
            LevelObject::Grass,
            LevelObject::Grass,
        ],
        [
            LevelObject::Grass,
            LevelObject::Grass,
            LevelObject::Grass,
            LevelObject::Grass,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Grass,
            LevelObject::Grass,
            LevelObject::Grass,
            LevelObject::Grass,
        ],
        [
            LevelObject::Grass,
            LevelObject::Grass,
            LevelObject::Grass,
            LevelObject::Grass,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Grass,
            LevelObject::Grass,
            LevelObject::Grass,
            LevelObject::Grass,
        ],
        [
            LevelObject::Grass,
            LevelObject::Grass,
            LevelObject::Grass,
            LevelObject::Grass,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Grass,
            LevelObject::Grass,
            LevelObject::Grass,
            LevelObject::Grass,
        ],
        [
            LevelObject::Grass,
            LevelObject::Grass,
            LevelObject::Grass,
            LevelObject::Grass,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Grass,
            LevelObject::Grass,
            LevelObject::Grass,
            LevelObject::Grass,
        ],
        [
            LevelObject::Grass,
            LevelObject::Grass,
            LevelObject::Grass,
            LevelObject::Grass,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Grass,
            LevelObject::Grass,
            LevelObject::Grass,
            LevelObject::Grass,
        ],
        [
            LevelObject::Grass,
            LevelObject::Grass,
            LevelObject::Grass,
            LevelObject::Grass,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Grass,
            LevelObject::Grass,
            LevelObject::Grass,
            LevelObject::Grass,
        ],
        [
            LevelObject::Grass,
            LevelObject::Grass,
            LevelObject::Grass,
            LevelObject::Grass,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Grass,
            LevelObject::Grass,
            LevelObject::Grass,
            LevelObject::Grass,
        ],
        [
            LevelObject::Grass,
            LevelObject::Grass,
            LevelObject::Grass,
            LevelObject::Grass,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Grass,
            LevelObject::Grass,
            LevelObject::Grass,
            LevelObject::Grass,
        ],
        [
            LevelObject::Grass,
            LevelObject::Grass,
            LevelObject::Grass,
            LevelObject::Grass,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Grass,
            LevelObject::Grass,
            LevelObject::Grass,
            LevelObject::Grass,
        ],
        [
            LevelObject::Grass,
            LevelObject::Grass,
            LevelObject::Grass,
            LevelObject::Grass,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Grass,
            LevelObject::Grass,
            LevelObject::Grass,
            LevelObject::Grass,
        ],
        [
            LevelObject::Grass,
            LevelObject::Grass,
            LevelObject::Grass,
            LevelObject::Grass,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Grass,
            LevelObject::Grass,
            LevelObject::Grass,
            LevelObject::Grass,
        ],
        [
            LevelObject::Grass,
            LevelObject::Grass,
            LevelObject::Grass,
            LevelObject::Grass,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Grass,
            LevelObject::Grass,
            LevelObject::Grass,
            LevelObject::Grass,
        ],
        [
            LevelObject::Grass,
            LevelObject::Grass,
            LevelObject::Grass,
            LevelObject::Grass,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Grass,
            LevelObject::Grass,
            LevelObject::Grass,
            LevelObject::Grass,
        ],
        [
            LevelObject::Grass,
            LevelObject::Grass,
            LevelObject::Grass,
            LevelObject::Grass,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Gravel,
            LevelObject::Gravel,
            LevelObject::Gravel,
            LevelObject::Gravel,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Grass,
            LevelObject::Grass,
            LevelObject::Grass,
            LevelObject::Grass,
        ],
        [
            LevelObject::Grass,
            LevelObject::Grass,
            LevelObject::Grass,
            LevelObject::Grass,
            LevelObject::Grass,
            LevelObject::Grass,
            LevelObject::Grass,
            LevelObject::Grass,
            LevelObject::Gravel,
            LevelObject::Gravel,
            LevelObject::Gravel,
            LevelObject::Gravel,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Grass,
            LevelObject::Grass,
            LevelObject::Grass,
            LevelObject::Grass,
        ],
        [
            LevelObject::Grass,
            LevelObject::Grass,
            LevelObject::Grass,
            LevelObject::Grass,
            LevelObject::Grass,
            LevelObject::Grass,
            LevelObject::Grass,
            LevelObject::Grass,
            LevelObject::Grass,
            LevelObject::Gravel,
            LevelObject::Gravel,
            LevelObject::Gravel,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Floor,
            LevelObject::Grass,
            LevelObject::Grass,
            LevelObject::Grass,
            LevelObject::Grass,
        ],
        [LevelObject::Grass; LEVEL_SIZE.x as usize],
        [LevelObject::Grass; LEVEL_SIZE.x as usize],
        [LevelObject::Grass; LEVEL_SIZE.x as usize],
        [LevelObject::Grass; LEVEL_SIZE.x as usize],
    ],
    [
        [LevelObject::Nothing; LEVEL_SIZE.x as usize],
        [LevelObject::Nothing; LEVEL_SIZE.x as usize],
        [LevelObject::Nothing; LEVEL_SIZE.x as usize],
        [LevelObject::Nothing; LEVEL_SIZE.x as usize],
        [
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::TopLeftWall,
            LevelObject::TopWall,
            LevelObject::TopWall,
            LevelObject::TopWall,
            LevelObject::TopWall,
            LevelObject::TopRightWall,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
        ],
        [
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::LeftWall,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::RightWall,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
        ],
        [
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::LeftWall,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::RightWall,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
        ],
        [
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::TopLeftWall,
            LevelObject::TopWall,
            LevelObject::TopWall,
            LevelObject::TopWall,
            LevelObject::TopLeftCorner,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::TopRightCorner,
            LevelObject::TopWall,
            LevelObject::TopWall,
            LevelObject::TopWall,
            LevelObject::TopRightWall,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
        ],
        [
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::LeftWall,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::TopLeftWall,
            LevelObject::TopWall,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::TopRightWall,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::RightWall,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
        ],
        [
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::LeftWall,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::LeftWall,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::RightWall,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
        ],
        [
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::BottomLeftWall,
            LevelObject::BottomWall,
            LevelObject::BottomWall,
            LevelObject::BottomWall,
            LevelObject::LeftWall,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::RightWall,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
        ],
        [
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::LeftWall,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::LeftWall,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::RightWall,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
        ],
        [
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::LeftWall,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::BottomLeftWall,
            LevelObject::BottomWall,
            LevelObject::Nothing,
            LevelObject::BottomWall,
            LevelObject::BottomRightWall,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::RightWall,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
        ],
        [
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::LeftWall,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::LeftWall,
            LevelObject::BottomWall,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::RightWall,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
        ],
        [
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::LeftWall,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::LeftWall,
            LevelObject::LeftWall,
            LevelObject::Nothing,
            LevelObject::RightWall,
            LevelObject::TopWall,
            LevelObject::Nothing,
            LevelObject::BottomLeftWall,
            LevelObject::BottomRightWall,
            LevelObject::Nothing,
            LevelObject::TopRightWall,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
        ],
        [
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::TopLeftWall,
            LevelObject::Nothing,
            LevelObject::TopRightWall,
            LevelObject::Nothing,
            LevelObject::LeftWall,
            LevelObject::LeftWall,
            LevelObject::Nothing,
            LevelObject::RightWall,
            LevelObject::Nothing,
            LevelObject::Player,
            LevelObject::Nothing,
            LevelObject::LeftWall,
            LevelObject::Nothing,
            LevelObject::RightWall,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
        ],
        [
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::BottomLeftWall,
            LevelObject::Nothing,
            LevelObject::RightWall,
            LevelObject::Nothing,
            LevelObject::LeftWall,
            LevelObject::LeftWall,
            LevelObject::Nothing,
            LevelObject::RightWall,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::LeftWall,
            LevelObject::Nothing,
            LevelObject::RightWall,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
        ],
        [
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::LeftWall,
            LevelObject::Nothing,
            LevelObject::RightWall,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::RightWall,
            LevelObject::TopWall,
            LevelObject::TopWall,
            LevelObject::TopWall,
            LevelObject::TopWall,
            LevelObject::TopWall,
            LevelObject::TopRightWall,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
        ],
        [
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::UShapedWall,
            LevelObject::Nothing,
            LevelObject::UShapedWall,
            LevelObject::BottomWall,
            LevelObject::LeftWall,
            LevelObject::LeftWall,
            LevelObject::Nothing,
            LevelObject::RightWall,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::RightWall,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
        ],
        [
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::LeftWall,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::BottomLeftWall,
            LevelObject::BottomLeftWall,
            LevelObject::Nothing,
            LevelObject::BottomRightWall,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::RightWall,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
        ],
        [
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::BottomLeftWall,
            LevelObject::BottomWall,
            LevelObject::BottomWall,
            LevelObject::BottomWall,
            LevelObject::LeftWall,
            LevelObject::Gravel,
            LevelObject::Gravel,
            LevelObject::RightWall,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::RightWall,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
        ],
        [
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Gravel,
            LevelObject::Gravel,
            LevelObject::Gravel,
            LevelObject::RightWall,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::RightWall,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
        ],
        [
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Gravel,
            LevelObject::Gravel,
            LevelObject::RightWall,
            LevelObject::BottomWall,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::BottomRightWall,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
        ],
        [LevelObject::Nothing; LEVEL_SIZE.x as usize],
        [LevelObject::Nothing; LEVEL_SIZE.x as usize],
        [LevelObject::Nothing; LEVEL_SIZE.x as usize],
        [LevelObject::Nothing; LEVEL_SIZE.x as usize],
    ],
];

pub fn spawn_level_objects(
    mut cmds: Commands,
    tile_tex_atlas: Res<TextureAtlasOwner<Tile>>,
    player_tex_atlas: Res<TextureAtlasOwner<Player>>,
) {
    for z in 0..LEVEL_SIZE.z as usize {
        for y in 0..LEVEL_SIZE.y as usize {
            for x in 0..LEVEL_SIZE.x as usize {
                let lvl_obj = LEVEL_LAYOUT[z][y][x];
                let pos = (Transform::from_translation(
                    (-Vec2::new(LEVEL_SIZE.x - 1., LEVEL_SIZE.y - 1.) * TILE_SIZE / 2.)
                        .extend(default()),
                ) * Transform::from_translation(
                    (Vec2::new(x as f32, LEVEL_SIZE.y - y as f32 - 1.) * TILE_SIZE)
                        .extend(default()),
                ))
                .translation
                .truncate();
                match lvl_obj {
                    LevelObject::Nothing => (),
                    LevelObject::Player => player::spawn_player(&mut cmds, pos, &player_tex_atlas),
                    _ => tile::spawn_tile(
                        &mut cmds,
                        pos,
                        z as f32,
                        &tile_tex_atlas,
                        lvl_obj.id(),
                        lvl_obj,
                    ),
                }
            }
        }
    }
}

pub fn level_plugin(app: &mut App) {
    app.add_systems(OnEnter(GameState::Playing), spawn_level_objects);
}
