use {
    super::{
        asset_owner::TextureAtlasOwner,
        player::{self, Player},
        tile::{self, Tile, TILE_SIZE},
        GameState,
    },
    bevy::prelude::*,
};

pub const LEVEL_SIZE: Vec3 = Vec3::new(22., 27., 2.);

#[repr(usize)]
#[derive(Copy, Clone)]
pub enum LevelObject {
    Grass1 = 0,
    Grass2 = 1,
    Grass3 = 2,
    Grass4 = 3,
    Dirt1 = 4,
    Dirt2 = 5,
    Gravel1 = 6,
    Gravel2 = 7,
    Gravel3 = 8,
    Gravel4 = 9,
    Water1 = 18,
    Water2 = 19,
    Floor1 = 95,
    Floor2 = 96,
    BrokenFloor1 = 98,
    BrokenFloor2 = 99,
    BrokenFloor3 = 100,
    SinglePillow = 101,
    SingleMiddle = 74,
    SingleFoot = 47,
    DoublePillow1 = 102,
    DoublePillow2 = 103,
    DoubleMiddle1 = 75,
    DoubleMiddle2 = 76,
    DoubleFoot1 = 48,
    DoubleFoot2 = 49,
    WallTopLeft = 124,
    WallTopRight = 125,
    WallBottomLeft = 151,
    WallBottomRight = 152,
    WallLeft = 175,
    WallRight = 176,
    WallTop = 202,
    WallBottom = 203,
    Stove = 323,
    Sink = 322,
    BigTv1 = 531,
    BigTv2 = 532,
    SmallTv = 536,
    Couch1 = 500,
    Couch2 = 501,
    Couch3 = 502,
    Recliner = 504,
    BedsideTable = 478,
    CoffeeTable = 505,
    Chair = 477,
    ShatteredGlass1 = 263,
    ShatteredGlass2 = 290,
    WoodPlank = 264,
    Debris1 = 291,
    Debris2 = 292,
    OilSpill = 319,
    KitchenTop = 320,
    TreeTopLeft = 180,
    TreeTopRight = 181,
    TreeBottomLeft = 207,
    TreeBottomRight = 208,
    Bush1 = 182,
    Bush2 = 209,
    FallenLeaves = 212,
    Box1 = 128,
    Box2 = 129,
    Box3 = 155,
    Box4 = 156,
    UWall = 123,
    Marble = 11,
    CornerTopLeft = 199,
    CornerTopRight = 198,
    CornerBottomRight = 171,
    CornerBottomLeft = 172,
    Nothing = usize::MAX,
    Player = usize::MAX - 1,
}

const LEVEL_LAYOUT: [[[LevelObject; LEVEL_SIZE.x as usize]; LEVEL_SIZE.y as usize];
    LEVEL_SIZE.z as usize] = [
    [
        [LevelObject::Grass1; LEVEL_SIZE.x as usize],
        [LevelObject::Grass1; LEVEL_SIZE.x as usize],
        [LevelObject::Grass1; LEVEL_SIZE.x as usize],
        [LevelObject::Grass1; LEVEL_SIZE.x as usize],
        [
            LevelObject::Grass1,
            LevelObject::Grass1,
            LevelObject::Grass1,
            LevelObject::Grass1,
            LevelObject::Grass1,
            LevelObject::Grass1,
            LevelObject::Grass1,
            LevelObject::Grass1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Grass1,
            LevelObject::Grass1,
            LevelObject::Grass1,
            LevelObject::Grass1,
            LevelObject::Grass1,
            LevelObject::Grass1,
            LevelObject::Grass1,
            LevelObject::Grass1,
        ],
        [
            LevelObject::Grass1,
            LevelObject::Grass1,
            LevelObject::Grass1,
            LevelObject::Grass1,
            LevelObject::Grass1,
            LevelObject::Grass1,
            LevelObject::Grass1,
            LevelObject::Grass1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Grass1,
            LevelObject::Grass1,
            LevelObject::Grass1,
            LevelObject::Grass1,
            LevelObject::Grass1,
            LevelObject::Grass1,
            LevelObject::Grass1,
            LevelObject::Grass1,
        ],
        [
            LevelObject::Grass1,
            LevelObject::Grass1,
            LevelObject::Grass1,
            LevelObject::Grass1,
            LevelObject::Grass1,
            LevelObject::Grass1,
            LevelObject::Grass1,
            LevelObject::Grass1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Grass1,
            LevelObject::Grass1,
            LevelObject::Grass1,
            LevelObject::Grass1,
            LevelObject::Grass1,
            LevelObject::Grass1,
            LevelObject::Grass1,
            LevelObject::Grass1,
        ],
        [
            LevelObject::Grass1,
            LevelObject::Grass1,
            LevelObject::Grass1,
            LevelObject::Grass1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Grass1,
            LevelObject::Grass1,
            LevelObject::Grass1,
            LevelObject::Grass1,
        ],
        [
            LevelObject::Grass1,
            LevelObject::Grass1,
            LevelObject::Grass1,
            LevelObject::Grass1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Grass1,
            LevelObject::Grass1,
            LevelObject::Grass1,
            LevelObject::Grass1,
        ],
        [
            LevelObject::Grass1,
            LevelObject::Grass1,
            LevelObject::Grass1,
            LevelObject::Grass1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Grass1,
            LevelObject::Grass1,
            LevelObject::Grass1,
            LevelObject::Grass1,
        ],
        [
            LevelObject::Grass1,
            LevelObject::Grass1,
            LevelObject::Grass1,
            LevelObject::Grass1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Grass1,
            LevelObject::Grass1,
            LevelObject::Grass1,
            LevelObject::Grass1,
        ],
        [
            LevelObject::Grass1,
            LevelObject::Grass1,
            LevelObject::Grass1,
            LevelObject::Grass1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Grass1,
            LevelObject::Grass1,
            LevelObject::Grass1,
            LevelObject::Grass1,
        ],
        [
            LevelObject::Grass1,
            LevelObject::Grass1,
            LevelObject::Grass1,
            LevelObject::Grass1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Grass1,
            LevelObject::Grass1,
            LevelObject::Grass1,
            LevelObject::Grass1,
        ],
        [
            LevelObject::Grass1,
            LevelObject::Grass1,
            LevelObject::Grass1,
            LevelObject::Grass1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Grass1,
            LevelObject::Grass1,
            LevelObject::Grass1,
            LevelObject::Grass1,
        ],
        [
            LevelObject::Grass1,
            LevelObject::Grass1,
            LevelObject::Grass1,
            LevelObject::Grass1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Grass1,
            LevelObject::Grass1,
            LevelObject::Grass1,
            LevelObject::Grass1,
        ],
        [
            LevelObject::Grass1,
            LevelObject::Grass1,
            LevelObject::Grass1,
            LevelObject::Grass1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Grass1,
            LevelObject::Grass1,
            LevelObject::Grass1,
            LevelObject::Grass1,
        ],
        [
            LevelObject::Grass1,
            LevelObject::Grass1,
            LevelObject::Grass1,
            LevelObject::Grass1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Grass1,
            LevelObject::Grass1,
            LevelObject::Grass1,
            LevelObject::Grass1,
        ],
        [
            LevelObject::Grass1,
            LevelObject::Grass1,
            LevelObject::Grass1,
            LevelObject::Grass1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Grass1,
            LevelObject::Grass1,
            LevelObject::Grass1,
            LevelObject::Grass1,
        ],
        [
            LevelObject::Grass1,
            LevelObject::Grass1,
            LevelObject::Grass1,
            LevelObject::Grass1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Grass1,
            LevelObject::Grass1,
            LevelObject::Grass1,
            LevelObject::Grass1,
        ],
        [
            LevelObject::Grass1,
            LevelObject::Grass1,
            LevelObject::Grass1,
            LevelObject::Grass1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Grass1,
            LevelObject::Grass1,
            LevelObject::Grass1,
            LevelObject::Grass1,
        ],
        [
            LevelObject::Grass1,
            LevelObject::Grass1,
            LevelObject::Grass1,
            LevelObject::Grass1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Gravel1,
            LevelObject::Gravel1,
            LevelObject::Gravel1,
            LevelObject::Gravel1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Grass1,
            LevelObject::Grass1,
            LevelObject::Grass1,
            LevelObject::Grass1,
        ],
        [
            LevelObject::Grass1,
            LevelObject::Grass1,
            LevelObject::Grass1,
            LevelObject::Grass1,
            LevelObject::Grass1,
            LevelObject::Grass1,
            LevelObject::Grass1,
            LevelObject::Grass1,
            LevelObject::Gravel1,
            LevelObject::Gravel1,
            LevelObject::Gravel1,
            LevelObject::Gravel1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Grass1,
            LevelObject::Grass1,
            LevelObject::Grass1,
            LevelObject::Grass1,
        ],
        [
            LevelObject::Grass1,
            LevelObject::Grass1,
            LevelObject::Grass1,
            LevelObject::Grass1,
            LevelObject::Grass1,
            LevelObject::Grass1,
            LevelObject::Grass1,
            LevelObject::Grass1,
            LevelObject::Grass1,
            LevelObject::Gravel1,
            LevelObject::Gravel1,
            LevelObject::Gravel1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Floor1,
            LevelObject::Grass1,
            LevelObject::Grass1,
            LevelObject::Grass1,
            LevelObject::Grass1,
        ],
        [LevelObject::Grass1; LEVEL_SIZE.x as usize],
        [LevelObject::Grass1; LEVEL_SIZE.x as usize],
        [LevelObject::Grass1; LEVEL_SIZE.x as usize],
        [LevelObject::Grass1; LEVEL_SIZE.x as usize],
    ],
    [
        [LevelObject::Nothing; LEVEL_SIZE.x as usize],
        [LevelObject::Nothing; LEVEL_SIZE.x as usize],
        [LevelObject::Nothing; LEVEL_SIZE.x as usize],
        [LevelObject::Nothing; LEVEL_SIZE.x as usize],
        [
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::WallTopLeft,
            LevelObject::WallTop,
            LevelObject::WallTop,
            LevelObject::WallTop,
            LevelObject::WallTop,
            LevelObject::WallTopRight,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
        ],
        [
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::WallLeft,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::WallRight,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
        ],
        [
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::WallLeft,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::WallRight,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
        ],
        [
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::WallTopLeft,
            LevelObject::WallTop,
            LevelObject::WallTop,
            LevelObject::WallTop,
            LevelObject::CornerTopLeft,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::CornerTopRight,
            LevelObject::WallTop,
            LevelObject::WallTop,
            LevelObject::WallTop,
            LevelObject::WallTopRight,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
        ],
        [
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::WallLeft,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::WallTopLeft,
            LevelObject::WallTop,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::WallTopRight,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::WallRight,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
        ],
        [
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::WallLeft,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::WallLeft,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::WallRight,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
        ],
        [
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::WallBottomLeft,
            LevelObject::WallBottom,
            LevelObject::WallBottom,
            LevelObject::WallBottom,
            LevelObject::WallLeft,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::WallRight,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
        ],
        [
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::WallLeft,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::WallLeft,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::WallRight,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
        ],
        [
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::WallLeft,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::WallBottomLeft,
            LevelObject::WallBottom,
            LevelObject::Nothing,
            LevelObject::WallBottom,
            LevelObject::WallBottomRight,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::WallRight,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
        ],
        [
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::WallLeft,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::WallLeft,
            LevelObject::WallBottom,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::WallRight,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
        ],
        [
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::WallLeft,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::WallLeft,
            LevelObject::WallLeft,
            LevelObject::Nothing,
            LevelObject::WallRight,
            LevelObject::WallTop,
            LevelObject::Nothing,
            LevelObject::WallBottomLeft,
            LevelObject::WallBottomRight,
            LevelObject::Nothing,
            LevelObject::WallTopRight,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
        ],
        [
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::WallTopLeft,
            LevelObject::Nothing,
            LevelObject::WallTopRight,
            LevelObject::Nothing,
            LevelObject::WallLeft,
            LevelObject::WallLeft,
            LevelObject::Nothing,
            LevelObject::WallRight,
            LevelObject::Nothing,
            LevelObject::Player,
            LevelObject::Nothing,
            LevelObject::WallLeft,
            LevelObject::Nothing,
            LevelObject::WallRight,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
        ],
        [
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::WallBottomLeft,
            LevelObject::Nothing,
            LevelObject::WallRight,
            LevelObject::Nothing,
            LevelObject::WallLeft,
            LevelObject::WallLeft,
            LevelObject::Nothing,
            LevelObject::WallRight,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::WallLeft,
            LevelObject::Nothing,
            LevelObject::WallRight,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
        ],
        [
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::WallLeft,
            LevelObject::Nothing,
            LevelObject::WallRight,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::WallRight,
            LevelObject::WallTop,
            LevelObject::WallTop,
            LevelObject::WallTop,
            LevelObject::WallTop,
            LevelObject::WallTop,
            LevelObject::WallTopRight,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
        ],
        [
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::UWall,
            LevelObject::Nothing,
            LevelObject::UWall,
            LevelObject::WallBottom,
            LevelObject::WallLeft,
            LevelObject::WallLeft,
            LevelObject::Nothing,
            LevelObject::WallRight,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::WallRight,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
        ],
        [
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::WallLeft,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::WallBottomLeft,
            LevelObject::WallBottomLeft,
            LevelObject::Nothing,
            LevelObject::WallBottomRight,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::WallRight,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
        ],
        [
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::WallBottomLeft,
            LevelObject::WallBottom,
            LevelObject::WallBottom,
            LevelObject::WallBottom,
            LevelObject::WallLeft,
            LevelObject::Gravel1,
            LevelObject::Gravel1,
            LevelObject::WallRight,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::WallRight,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
        ],
        [
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Gravel1,
            LevelObject::Gravel1,
            LevelObject::Gravel1,
            LevelObject::WallRight,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::WallRight,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
        ],
        [
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Gravel1,
            LevelObject::Gravel1,
            LevelObject::WallRight,
            LevelObject::WallBottom,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::WallBottomRight,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
            LevelObject::Nothing,
        ],
        [LevelObject::Nothing; LEVEL_SIZE.x as usize],
        [LevelObject::Nothing; LEVEL_SIZE.x as usize],
        [LevelObject::Nothing; LEVEL_SIZE.x as usize],
        [LevelObject::Nothing; LEVEL_SIZE.x as usize],
    ],
];

pub fn spawn_level_objects(
    mut cmds: Commands,
    tile_tex_atlas: Res<TextureAtlasOwner<Tile>>,
    player_tex_atlas: Res<TextureAtlasOwner<Player>>,
) {
    for z in 0..LEVEL_SIZE.z as usize {
        for y in 0..LEVEL_SIZE.y as usize {
            for x in 0..LEVEL_SIZE.x as usize {
                let lvl_obj = LEVEL_LAYOUT[z][y][x];
                let pos = (Transform::from_translation(
                    (-Vec2::new(LEVEL_SIZE.x - 1., LEVEL_SIZE.y - 1.) * TILE_SIZE / 2.)
                        .extend(default()),
                ) * Transform::from_translation(
                    (Vec2::new(x as f32, LEVEL_SIZE.y - y as f32 - 1.) * TILE_SIZE)
                        .extend(default()),
                ))
                .translation
                .truncate();
                match lvl_obj {
                    LevelObject::Nothing => (),
                    LevelObject::Player => player::spawn_player(&mut cmds, pos, &player_tex_atlas),
                    _ => tile::spawn_tile(
                        &mut cmds,
                        pos,
                        z as f32,
                        &tile_tex_atlas,
                        lvl_obj as usize,
                        lvl_obj,
                    ),
                }
            }
        }
    }
}

pub fn level_plugin(app: &mut App) {
    app.add_systems(OnEnter(GameState::Playing), spawn_level_objects);
}
